Move common parts out from this project (#183)
* Move common parts out from this project

* tests: Only test help.1

diff --git a/5.7/test/run b/5.7/test/run
--- a/5.7/test/run
+++ b/5.7/test/run
@@ -384,18 +384,16 @@ run_doc_test() {
   local tmpdir=$(mktemp -d)
   local f
   echo "  Testing documentation in the container image"
-  # Extract the help files from the container
-  for f in /usr/share/container-scripts/mysql/README.md help.1 ; do
-    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/$(basename ${f})
-    # Check whether the files include some important information
-    for term in MYSQL_ROOT_PASSWORD volume 3306 ; do
-      if ! cat ${tmpdir}/$(basename ${f}) | grep -q -e "${term}" ; then
-        echo "ERROR: File /${f} does not include '${term}'."
-        return 1
-      fi
-    done
+  # Extract the help.1 file from the container
+  docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /help.1" >${tmpdir}/help.1
+  # Check whether the help.1 file includes some important information
+  for term in "MYSQL\_ROOT\_PASSWORD" volume 3306 ; do
+    if ! cat ${tmpdir}/help.1 | grep -F -q -e "${term}" ; then
+      echo "ERROR: File /help.1 does not include '${term}'."
+      return 1
+    fi
   done
-  # Check whether the files use the correct format
+  # Check whether the file uses the correct format
   if ! file ${tmpdir}/help.1 | grep -q roff ; then
     echo "ERROR: /help.1 is not in troff or groff format"
     return 1
