Let's incluce README.md in a topic directory, to allow more existing in one image
We also don't need to include README.md in the root, just help.1 should be enough.

diff --git a/5.6/test/run b/5.6/test/run
--- a/5.6/test/run
+++ b/5.6/test/run
@@ -380,27 +380,26 @@ function run_tests() {
   test_mysql "$container_ip" "$USER" "$PASS"
 }
 
-run_doc_check() {
+run_doc_test() {
   local tmpdir=$(mktemp -d)
+  local f
   echo "  Testing documentation in the container image"
   # Extract the help files from the container
-  for f in help.md help.1 ; do
-    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/${f}
+  for f in /usr/share/container-scripts/mysql/README.md help.1 ; do
+    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/$(basename ${f})
+    # Check whether the files include some important information
+    for term in MYSQL_ROOT_PASSWORD volume 3306 ; do
+      if ! cat ${tmpdir}/$(basename ${f}) | grep -q -e "${term}" ; then
+        echo "ERROR: File /${f} does not include '${term}'."
+        return 1
+      fi
+    done
   done
   # Check whether the files use the correct format
   if ! file ${tmpdir}/help.1 | grep -q roff ; then
     echo "ERROR: /help.1 is not in troff or groff format"
     return 1
   fi
-  # Check whether the files include some important information
-  for term in MYSQL_ROOT_PASSWORD volume 3306 ; do
-    for f in help.md help.1 ; do
-      if ! cat ${tmpdir}/${f} | grep -q -e "${term}" ; then
-        echo "ERROR: File /${f} does not include '${term}'."
-        return 1
-      fi
-    done
-  done
   echo "  Success!"
   echo
 }
@@ -427,6 +426,6 @@ run_change_password_test
 # Replication tests
 run_replication_test
 
-run_doc_check
+run_doc_test
 
 TESTSUITE_RESULT=0
